import type { ProductoCatalogo } from './types'

const U = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`

/** Figuras y merch real en Mercado Libre México */
export const COLECTIBLE_PRODUCTOS: ProductoCatalogo[] = [
  {
    id: 'fig-tanjiro',
    nombre: 'Nendoroid Tanjiro Kamado (2nd)',
    descripcion: 'Figura articulada oficial Good Smile — Demon Slayer.',
    imagen: U('photo-1601811833011-2039bfee4c4e'),
    url: 'https://www.mercadolibre.com.mx/nendoroid-tanjiro-kamado2nd-re-run/p/MLM24247928',
    cta: 'Ver en Mercado Libre',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Figura',
  },
  {
    id: 'fig-gojo',
    nombre: 'Figura Gojo Satoru — Jujutsu Kaisen',
    descripcion: 'Piezas de colección con alta demanda en México.',
    imagen: U('photo-1558068715-cd0014caa5df'),
    url: 'https://listado.mercadolibre.com.mx/figura-gojo-jujutsu-kaisen',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Tendencia',
  },
  {
    id: 'fig-luffy',
    nombre: 'Figura Luffy — One Piece',
    descripcion: 'Clásico de vitrina para fans del Sombrero de Paja.',
    imagen: U('photo-1578632767115-351597cf2477'),
    url: 'https://listado.mercadolibre.com.mx/figura-luffy-one-piece',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Clásico',
  },
  {
    id: 'fig-levi',
    nombre: 'Figura Levi — Attack on Titan',
    descripcion: 'Uno de los personajes más buscados en figuras de acción.',
    imagen: U('photo-1618366712010-f4ae9c647dcb'),
    url: 'https://listado.mercadolibre.com.mx/figura-levi-attack-on-titan',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Top ventas',
  },
  {
    id: 'tcg-pokemon',
    nombre: 'Booster Pokémon TCG Español',
    descripcion: 'Sobres y cajas oficiales para armar o ampliar tu mazo.',
    imagen: U('photo-1612036782182-4b0c4fbb632c'),
    url: 'https://listado.mercadolibre.com.mx/pokemon-tcg-booster-sobre-espanol',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'TCG',
  },
  {
    id: 'plush-anime',
    nombre: 'Peluche anime oficial',
    descripcion: 'Regalo suave — busca licencias de series que te gusten.',
    imagen: U('photo-1566576910341-82a75c0b4145'),
    url: 'https://listado.mercadolibre.com.mx/peluche-anime-oficial',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Regalo',
  },
  {
    id: 'poster-scroll',
    nombre: 'Wall scroll anime',
    descripcion: 'Posters y lonas para decorar cuarto o setup.',
    imagen: U('photo-1513519245088-0e12902e35a7'),
    url: 'https://listado.mercadolibre.com.mx/wall-scroll-anime',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Decoración',
  },
  {
    id: 'bluray-anime',
    nombre: 'Blu-ray anime edición',
    descripcion: 'Ediciones físicas para quien ama el rewatch sin streaming.',
    imagen: U('photo-1598896846378-2acb08c8b812'),
    url: 'https://listado.mercadolibre.com.mx/blu-ray-anime-edicion',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Físico',
  },
]
