import type { ProductoAfiliado } from './types'

const U = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`

export const COLECTIBLE_PRODUCTOS: ProductoAfiliado[] = [
  {
    id: 'fig-tanjiro',
    nombre: 'Figura Tanjiro — Demon Slayer',
    descripcion: 'Nendoroid / figura de acción para vitrina otaku.',
    imagen: U('photo-1601811833011-2039bfee4c4e'),
    partner: 'amazon',
    query: 'demon slayer tanjiro figura nendoroid',
    precioDesde: 'Desde $899',
    badge: 'Figura',
  },
  {
    id: 'fig-gojo',
    nombre: 'Figura Gojo — Jujutsu Kaisen',
    descripcion: 'Pieza con mucha presencia para estantería.',
    imagen: U('photo-1558068715-cd0014caa5df'),
    partner: 'mercadolibre',
    query: 'jujutsu kaisen gojo figura',
    precioDesde: 'Desde $750',
    badge: 'Tendencia',
  },
  {
    id: 'fig-luffy',
    nombre: 'Figura Luffy — One Piece',
    descripcion: 'Clásico de colección que no falla como regalo.',
    imagen: U('photo-1578632767115-351597cf2477'),
    partner: 'amazon',
    query: 'one piece luffy figura',
    precioDesde: 'Desde $1,200',
    badge: 'Clásico',
  },
  {
    id: 'fig-levi',
    nombre: 'Figura Levi — Attack on Titan',
    descripcion: 'Uno de los personajes más buscados en figuras.',
    imagen: U('photo-1618366712010-f4ae9c647dcb'),
    partner: 'amazon',
    query: 'attack on titan levi figura',
    precioDesde: 'Desde $950',
    badge: 'Top ventas',
  },
  {
    id: 'tcg-pokemon',
    nombre: 'Booster Pokémon TCG',
    descripcion: 'Sobres y cajas para armar o ampliar tu mazo.',
    imagen: U('photo-1612036782182-4b0c4fbb632c'),
    partner: 'mercadolibre',
    query: 'pokemon tcg booster caja',
    precioDesde: 'Desde $350',
    badge: 'TCG',
  },
  {
    id: 'plush-anime',
    nombre: 'Peluche anime kawaii',
    descripcion: 'Regalo suave para fans de cualquier edad.',
    imagen: U('photo-1566576910341-82a75c0b4145'),
    partner: 'amazon',
    query: 'peluche anime kawaii',
    precioDesde: 'Desde $299',
    badge: 'Regalo',
  },
  {
    id: 'poster-scroll',
    nombre: 'Poster & wall scroll',
    descripcion: 'Arte para pared con estética de sala de anime.',
    imagen: U('photo-1513519245088-0e12902e35a7'),
    partner: 'mercadolibre',
    query: 'poster anime wall scroll',
    precioDesde: 'Desde $199',
    badge: 'Decoración',
  },
  {
    id: 'bluray-anime',
    nombre: 'Blu-ray anime edición',
    descripcion: 'Colección física para quien ama el rewatch.',
    imagen: U('photo-1598896846378-2acb08c8b812'),
    partner: 'amazon',
    query: 'anime blu ray coleccion edicion',
    precioDesde: 'Desde $499',
    badge: 'Físico',
  },
  {
    id: 'fig-economica',
    nombre: 'Figura accesible',
    descripcion: 'Entrada a coleccionar sin gastar de más.',
    imagen: U('photo-1558068715-cd0014caa5df'),
    partner: 'mercadolibre',
    query: 'figura anime barata coleccion',
    precioDesde: 'Desde $399',
    badge: 'Económico',
  },
]
