export type { ProductoCatalogo, ProductoAfiliado } from './types'
export { COLECTIBLE_PRODUCTOS } from './coleccionables'
export { TECH_PRODUCTOS } from './tecnologia'
export { MANGA_PRODUCTOS, mangaProductosParaTitulo } from './mangas'
export { enrichProductosConMal } from './enrich'
