import type { ProductoCatalogo } from './types'

const U = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`

/** Productos reales en Mercado Libre México — URLs verificadas en tienda */
export const TECH_PRODUCTOS: ProductoCatalogo[] = [
  {
    id: 'tech-anc',
    nombre: 'Soundcore Q20i — cancelación activa',
    descripcion: 'Audífonos over-ear con ANC híbrido, ideales para maratones nocturnas.',
    imagen: U('photo-1505740420928-5e560c06d30e'),
    url: 'https://articulo.mercadolibre.com.mx/MLM-1982632085-audifonos-hibridos-soundcore-q20i-cancelacion-activa-negro-_JM',
    cta: 'Ver en Mercado Libre',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Audio',
  },
  {
    id: 'tech-monitor',
    nombre: 'MSI G272 — monitor 144 Hz IPS',
    descripcion: '27" Full HD, 1 ms MPRT y G-Sync Compatible para anime y juegos fluidos.',
    imagen: U('photo-1527443157979-24770039a5a5'),
    url: 'https://articulo.mercadolibre.com.mx/MLM-1432193565-monitor-gamer-msi-g272-144hz-1ms-ips-nvidia-g-sync-_JM',
    cta: 'Ver en Mercado Libre',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Pantalla',
  },
  {
    id: 'tech-tablet',
    nombre: 'Samsung Galaxy Tab A9+',
    descripcion: 'Tablet 11" para manga digital, novelas y apps de streaming.',
    imagen: U('photo-1544244015-0df4b3ffc6b0'),
    url: 'https://www.mercadolibre.com.mx/samsung-galaxy-tab-a9-plus/p/MLM20485782',
    cta: 'Ver en Mercado Libre',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Manga',
  },
  {
    id: 'tech-rgb',
    nombre: 'Barra LED RGB para monitor',
    descripcion: 'Luz ambiental USB para escritorio otaku o setup de streaming.',
    imagen: U('photo-1558618666-fcd25c85cd64'),
    url: 'https://listado.mercadolibre.com.mx/barra-luz-led-rgb-monitor',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Desde ~$399',
    badge: 'Ambiente',
  },
  {
    id: 'tech-silla',
    nombre: 'Silla gamer ergonómica',
    descripcion: 'Respaldo reclinable y soporte lumbar para temporadas largas.',
    imagen: U('photo-1598550470879-326188d11385'),
    url: 'https://listado.mercadolibre.com.mx/silla-gamer-ergonomica',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Confort',
  },
  {
    id: 'tech-proyector',
    nombre: 'Proyector portátil Full HD',
    descripcion: 'Mini cine en casa — anime en la pared con WiFi y altavoz integrado.',
    imagen: U('photo-1478720568477-152d9b184e63'),
    url: 'https://listado.mercadolibre.com.mx/proyector-portatil-full-hd-wifi',
    cta: 'Ver opciones',
    tienda: 'Mercado Libre',
    precioDesde: 'Consultar precio',
    badge: 'Cine',
  },
]
